name: Basic Example
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: spring-1
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: rafoelhonrado/testing-spring-api-rest-karate
        path: testing
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: nohup mvn spring-boot:run &
      working-directory: ./main/product-api-service
    - name: Run with Maven
      run: mvn test -Dkarate.options="--tags @crear"
      working-directory: ./testing/product-api-service-karate
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.6
      with:
        filename: results.zip
        path: .
        directory: ./testing/product-api-service-karate/target/karate-reports
        type: zip
    - name: View Current Directory
      run: pwd; ls;
      working-directory: ./testing/product-api-service-karate/target/karate-reports
    - name: Send email
      uses: dawidd6/action-send-mail@v3.11.0
      with:
        server_address: ${{secrets.EMAIL_SERVER}}
        server_port: 465
        secure: true
        username: ${{secrets.EMAIL_USERNAME}}
        password: ${{secrets.EMAIL_PASS}}
        subject: Pruebas completadas
        # Recipients mail addresses (separated with comma)
        to: rafoelhonrado@hotmail.com,raforeynacamones@gmail.com
        from: admin@test.com
        body: Este es un mensaje de confirmacion de las pruebas
        attachments: attachments.zip,git.diff,./testing/product-api-service-karate/target/karate-reports/results.zip


              
          
      

