name: Product API Pipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: spring-1
    steps:
    - name: Checkout Product API
      uses: actions/checkout@v4
      with:
        path: main
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20.x'
    - name: Install Newman
      run: npm install -g newman;
    - name: Install Newman HTML reporter
      run: npm install -g newman-reporter-html;
    - name: Install Newman HTML Extra reporter
      run: npm install -g newman-reporter-htmlextra;
    - name: Setup JDK 17 environment
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Generate build using maven
      run: nohup mvn spring-boot:run &
      working-directory: ./main/product-api-service
    - name: Wait for service to start
      run: sleep 60  # Wait for 60 seconds. Adjust this duration based on your service startup time.      
    - name: Run postman collection (Requests)
      run: newman run producto_api.json -d productos.csv --folder "Happy Path" --environment env.json -r cli,json,junit,html,htmlextra
      working-directory: ./main/product-api-service/extra
    - name: Zip files 
      uses: TheDoctor0/zip-release@0.7.6
      with:
        filename: results.zip
        path: .
        directory: ./main/product-api-service/extra
        type: zip
    - name: Send email
      uses: dawidd6/action-send-mail@v3.11.0
      with:
        server_address: ${{secrets.EMAIL_SERVER}}
        server_port: 465
        secure: true
        username: ${{secrets.EMAIL_USERNAME}}
        password: ${{secrets.EMAIL_PASS}}
        subject: Pruebas completadas
        # Recipients mail addresses (separated with comma)
        to: rafoelhonrado@hotmail.com,raforeynacamones@gmail.com, VICTOR_AGAPITO@hotmail.com,yulianaalvarez671@gmail.com
        from: admin@test.com
        body: Este es un mensaje de confirmacion de las pruebas
        attachments: attachments.zip,git.diff,./main/product-api-service/extra/results.zip
