# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main
    - name: View Current Directory
      run: pwd; ls; 
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: rafoelhonrado/testing-spring-api-rest-karate
        path: testing
    - name: View Current Directory
      run: pwd; ls; 
    - name: Build with Maven
      run: mvn spring-boot:run
      working-directory: ./main/product-api-service
    - name: Build with Maven
      run: mvn test
      working-directory: ./main/product-api-service

